version: "3"

services:
  activemq:
    image: webcenter/activemq:latest
    restart: unless-stopped
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks: [backing-services]
    volumes: ["activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq"]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: cds4admin
      ACTIVEMQ_WRITE_LOGIN: cds
      ACTIVEMQ_WRITE_PASSWORD: cds4All
      ACTIVEMQ_READ_LOGIN: cds
      ACTIVEMQ_READ_PASSWORD: cds4All
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: cds4admin
      ACTIVEMQ_STATIC_QUEUES: Q.cds.common.DLQ 
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

volumes:
  activemq-data: {}

networks:
  backing-services:
    driver: bridge  
